In [15]:
# Importar librerías necesarias
import pandas as pd #Libreria para trabajar con tablas de datos
import numpy as np #Libreria para oepraciones matematicas t arrays numericos con el apodo np
import matplotlib.pyplot as plt #Libreria para realizar graficos basicos con el apodo plt
import seaborn as sns # Libreria para graficos mas esteticos y estadisticos con el apodo sns

# Configurar visualización
plt.style.use('seaborn-v0_8-darkgrid') #Se define el estilo visual de los graficos
sns.set_palette("Set2") # Se define la paleta de colores que usaran los graficos
plt.rcParams['figure.figsize'] = (12, 6)# Se define tamaño de graficos

print("Librerías importadas correctamente") #Muestra mensaje en pantalla para confirmar la improtacion de librerias correctamente
print(f"Pandas versión: {pd.__version__}")#Muestra la version de pandas instalado

Librerías importadas correctamente
Pandas versión: 2.2.3

In [16]:
# Cargar archivo CVS
ruta_archivo = "C:\\Users\\dally\\OneDrive - UNIR\\TRABAJO FIN DE MASTER\\tfm_informes-diagnostico-valvulas\\Data\\Dataset valvulas de control TY.csv" 
#Se define variable de ruta_archivo para que lo llame desde la carpeta si tiene alguna actualizacion
try:
    df = pd.read_csv(ruta_archivo, sep=';', encoding='utf-8') #Define en un dataframe el archivo cvs, separando las columnas
    print(f" Archivo cargado correctamente") #Se valida si el archivo fue cargado correctamente
    print(f" Dimensiones: {df.shape[0]} filas y {df.shape[1]} columnas") # Se indican las caracteristicas del dataframe
except FileNotFoundError: # En caso de no encontrar el archivo lanza error para verificacion de existencia
    print(f"ERROR: No se encontró el archivo en la ruta:")
    print(f"   {ruta_archivo}")
    print("\n Verifica que el archivo esté en la carpeta 'Data'")

# Mostrar las primeras filas
print("\n VISTA PREVIA DE LOS DATOS:")
df.head()

 Archivo cargado correctamente
 Dimensiones: 22 filas y 31 columnas

 VISTA PREVIA DE LOS DATOS:

,TIPO DE EQUIPO,TAG CUERPO,FABRICANTE CUERPO,MODELO CUERPO,SERIAL CUERPO,TAMAÑO CUERPO,ANSI CUERPO,MATERIAL CUERPO,MODELO ACTUADOR,FABRICANTE ACTUADOR,...,SIS POSICIONADOR,FECHA RECEPCIÓN,FRICCION RECOMENDADA,FRICCION MEDIDA,BANDA DE ERROR DINAMICA RECOMENDADA,BANDA DE ERROR DINAMICA MEDIDA,LINEALIDAD DINAMICA RECOMENDADA,LINEALIDAD DINAMICA MEDIDA,TORQUE - CARGA EN EL ASIENTO RECOMENDADA,TORQUE - CARGA EN EL ASIENTO MEDIDA
0,Válvula de control,PCV-5001,2,ET,2002094,3,#600,WCC,667,2,...,NaN,23/09/2025,50,100,"2,42","1,92","2,4","0,12","137,37","70,16"
1,Válvula de control,LCV-3055,2,EZ,20020954,1,#600,WCC,667,2,...,NaN,23/09/2025,15,1,"2,6","1,57","2,4","0,38","47,12","-7,16"
2,Válvula de control,FCV-3040,2,ET,20020955,3,#600,WCC,667,2,...,NaN,23/09/2025,50,46,"2,6","3,36","2,4","0,33","137,37","602,4"
3,Válvula de control,FCV-0120,2,V150,F000096200,3,#150,STL,2052,2,...,NaN,23/09/2025,250,134,"3,6","6,12","2,6","1,5",549,242
4,Válvula de control,FCV-4061,2,GX,F001354428,1,#300,STL,GX,2,...,NaN,23/09/2025,120,76,"2,42","1,44","2,4","0,31",335,"536,52"

In [17]:
# SELECCIONAR SOLO LAS COLUMNAS NECESARIAS PARA DIAGNÓSTICO

# Definir las columnas que queremos conservar
columnas_utiles = [
    'TAG CUERPO',                           # Identificador de la válvula
    'FRICCION RECOMENDADA',                 # Fricción recomendada
    'FRICCION MEDIDA',                      # Fricción medida
    'TORQUE - CARGA EN EL ASIENTO RECOMENDADA',  # Carga/Torque recomendada
    'TORQUE - CARGA EN EL ASIENTO MEDIDA',       # Carga/Torque medida
    'BANDA DE ERROR DINAMICA RECOMENDADA',      # Banda muerta recomendada
    'BANDA DE ERROR DINAMICA MEDIDA',           # Banda muerta medida
    'LINEALIDAD DINAMICA RECOMENDADA',          # Linealidad recomendada
    'LINEALIDAD DINAMICA MEDIDA'                # Linealidad medida
]

# Verificar qué columnas existen realmente en el DataFrame
columnas_existentes = [col for col in columnas_utiles if col in df.columns] # Itera sobre cada columna en columna_utiles
columnas_faltantes = [col for col in columnas_utiles if col not in df.columns]# Guarda las columnas que NO existen en el Dataframe

print(" VERIFICACIÓN DE COLUMNAS:")

if columnas_faltantes: #Si hay columnas faltantes, las muestra con su cantidad
    print(f" Columnas faltantes ({len(columnas_faltantes)}):")
    for col in columnas_faltantes:
        print(f"   - '{col}'")
else: #Si no hay faltantes, indica que todas están presentes
    print(" Todas las columnas necesarias están presentes")

print(f"\n Columnas a conservar ({len(columnas_existentes)}):")
for col in columnas_existentes:
    print(f"   - '{col}'")

# Crear nuevo DataFrame solo con las columnas útiles
df_diagnostico = df[columnas_existentes].copy()


print(f" NUEVO DATAFRAME:")
print(f"   Filas: {len(df_diagnostico)}")
print(f"   Columnas: {len(df_diagnostico.columns)}")

# Mostrar vista previa
print("\n VISTA PREVIA DEL NUEVO DATAFRAME:")
print("=" * 80)
df_diagnostico.head(22)

 VERIFICACIÓN DE COLUMNAS:
 Todas las columnas necesarias están presentes

 Columnas a conservar (9):
   - 'TAG CUERPO'
   - 'FRICCION RECOMENDADA'
   - 'FRICCION MEDIDA'
   - 'TORQUE - CARGA EN EL ASIENTO RECOMENDADA'
   - 'TORQUE - CARGA EN EL ASIENTO MEDIDA'
   - 'BANDA DE ERROR DINAMICA RECOMENDADA'
   - 'BANDA DE ERROR DINAMICA MEDIDA'
   - 'LINEALIDAD DINAMICA RECOMENDADA'
   - 'LINEALIDAD DINAMICA MEDIDA'
 NUEVO DATAFRAME:
   Filas: 22
   Columnas: 9

 VISTA PREVIA DEL NUEVO DATAFRAME:
================================================================================

,TAG CUERPO,FRICCION RECOMENDADA,FRICCION MEDIDA,TORQUE - CARGA EN EL ASIENTO RECOMENDADA,TORQUE - CARGA EN EL ASIENTO MEDIDA,BANDA DE ERROR DINAMICA RECOMENDADA,BANDA DE ERROR DINAMICA MEDIDA,LINEALIDAD DINAMICA RECOMENDADA,LINEALIDAD DINAMICA MEDIDA
0,PCV-5001,50,100,"137,37","70,16","2,42","1,92","2,4","0,12"
1,LCV-3055,15,1,"47,12","-7,16","2,6","1,57","2,4","0,38"
2,FCV-3040,50,46,"137,37","602,4","2,6","3,36","2,4","0,33"
3,FCV-0120,250,134,549,242,"3,6","6,12","2,6","1,5"
4,FCV-4061,120,76,335,"536,52","2,42","1,44","2,4","0,31"
5,LCV-4030,100,16,"180,22","75,41","2,6","2,05","2,4","0,18"
6,PCV-7050,44,25,"549,78","294,8","2,42",1,"2,4","0,14"
7,LCV-6040,149,34,"109,96","400,52","2,6","1,3","2,4","0,51"
8,TCV-6050,120,94,"251,33","802,28","2,6","1,12","2,4","0,26"
9,PCV-7070,44,25,"549,78","266,37","2,6","0,87","2,4","0,17"
10,TCV-6020,75,50,350,"275,4","2,6","2,2","2,4","0,08"
11,TCV-4100,44,44,"579,48","1185,61","2,6","1,26","2,4","0,12"
12,LCV-4150,60,51,"549,78","632,9","2,6","2,16","2,4","0,53"
13,FCV-4120,31,62,"137,37","735,72","2,42","1,46","2,4","0,42"
14,TCV-4070,0,0,450,77,"3,6","7,37","2,4","11,28"
15,PCV-7030,60,19,221,"140,59","2,6","1,19","2,4","0,2"
16,LCV-4020,50,59,"137,37","71,59","2,6","2,07","2,4","0,17"
17,PCV-4005,60,121,"94,25","631,77","2,42","1,47","2,4","0,53"
18,PCV-5002,0,0,150,117,"3,6","1,64","2,6","0,11"
19,PCV-1301,60,39,"235,48","654,5","2,6","1,55",2,"0,43"
20,PCV-6040,120,35,221,"1945,6","2,6","2,76","2,4","0,11"
21,PCV-4020,44,47,"549,78","558,01","2,6","2,96","2,4","0,11"

In [18]:
# CONVERTIR A NÚMEROS (ENTEROS O FLOTANTES) CONSERVANDO VALORES ORIGINALES

columnas_numericas = [
    'FRICCION RECOMENDADA', 'FRICCION MEDIDA',
    'TORQUE - CARGA EN EL ASIENTO RECOMENDADA', 'TORQUE - CARGA EN EL ASIENTO MEDIDA',
    'BANDA DE ERROR DINAMICA RECOMENDADA', 'BANDA DE ERROR DINAMICA MEDIDA',
    'LINEALIDAD DINAMICA RECOMENDADA', 'LINEALIDAD DINAMICA MEDIDA'
]

# FUNCIÓN PARA LIMPIAR Y CONVERTIR CADA VALOR A NÚMERO
def convertir_a_numero(valor):
    """Convierte un valor a número (int o float) conservando su valor original"""
    if pd.isna(valor):
        return np.nan
    if isinstance(valor, (int, float)):
        return valor
    if isinstance(valor, str):
        # Limpiar la cadena
        valor_limpio = valor.strip()
        # Reemplazar coma por punto (para decimales estilo europeo)
        valor_limpio = valor_limpio.replace(',', '.')
        # Eliminar espacios
        valor_limpio = valor_limpio.replace(' ', '')
        # Eliminar símbolos de porcentaje si los hay
        valor_limpio = valor_limpio.replace('%', '')
        # Eliminar otros caracteres no numéricos (excepto punto y signo menos)
        import re
        valor_limpio = re.sub(r'[^0-9.-]', '', valor_limpio)
        # Si está vacío, retornar NaN
        if valor_limpio == '' or valor_limpio == '-':
            return np.nan
        # Convertir a float
        try:
            num = float(valor_limpio)
            # Si es entero, convertir a int
            if num == int(num):
                return int(num)
            return num
        except:
            return np.nan
    return np.nan


# APLICAR CONVERSIÓN A TODAS LAS COLUMNAS

print("\n CONVIRTIENDO A NÚMEROS...")

for col in columnas_numericas:
    if col in df_diagnostico.columns:
        # Contar valores no numéricos antes
        no_numericos = df_diagnostico[col].apply(lambda x: not isinstance(x, (int, float)) if pd.notna(x) else False).sum()
        
        # Aplicar conversión
        df_diagnostico[col] = df_diagnostico[col].apply(convertir_a_numero)
        
        # Mostrar resultado
        tipo_final = df_diagnostico[col].dtype
        print(f"  {col}: {no_numericos} valores convertidos → tipo final: {tipo_final}")

# VERIFICAR RESULTADOS

print("\n VERIFICACIÓN FINAL:")

print(f"Filas totales: {len(df_diagnostico)} (ninguna fila fue eliminada)")

for col in columnas_numericas:
    if col in df_diagnostico.columns:
        print(f"  {col}: tipo = {df_diagnostico[col].dtype}")

# Mostrar vista previa
print("\nVISTA PREVIA DE LAS 22 VÁLVULAS (VALORES CONVERTIDOS):")
df_diagnostico[['TAG CUERPO'] + columnas_numericas].head(22)

 CONVIRTIENDO A NÚMEROS...
  FRICCION RECOMENDADA: 0 valores convertidos → tipo final: int64
  FRICCION MEDIDA: 0 valores convertidos → tipo final: int64
  TORQUE - CARGA EN EL ASIENTO RECOMENDADA: 22 valores convertidos → tipo final: float64
  TORQUE - CARGA EN EL ASIENTO MEDIDA: 22 valores convertidos → tipo final: float64
  BANDA DE ERROR DINAMICA RECOMENDADA: 22 valores convertidos → tipo final: float64
  BANDA DE ERROR DINAMICA MEDIDA: 22 valores convertidos → tipo final: float64
  LINEALIDAD DINAMICA RECOMENDADA: 22 valores convertidos → tipo final: float64
  LINEALIDAD DINAMICA MEDIDA: 22 valores convertidos → tipo final: float64

 VERIFICACIÓN FINAL:
Filas totales: 22 (ninguna fila fue eliminada)
  FRICCION RECOMENDADA: tipo = int64
  FRICCION MEDIDA: tipo = int64
  TORQUE - CARGA EN EL ASIENTO RECOMENDADA: tipo = float64
  TORQUE - CARGA EN EL ASIENTO MEDIDA: tipo = float64
  BANDA DE ERROR DINAMICA RECOMENDADA: tipo = float64
  BANDA DE ERROR DINAMICA MEDIDA: tipo = float64
  LINEALIDAD DINAMICA RECOMENDADA: tipo = float64
  LINEALIDAD DINAMICA MEDIDA: tipo = float64

VISTA PREVIA DE LAS 22 VÁLVULAS (VALORES CONVERTIDOS):

,TAG CUERPO,FRICCION RECOMENDADA,FRICCION MEDIDA,TORQUE - CARGA EN EL ASIENTO RECOMENDADA,TORQUE - CARGA EN EL ASIENTO MEDIDA,BANDA DE ERROR DINAMICA RECOMENDADA,BANDA DE ERROR DINAMICA MEDIDA,LINEALIDAD DINAMICA RECOMENDADA,LINEALIDAD DINAMICA MEDIDA
0,PCV-5001,50,100,137.37,70.16,2.42,1.92,2.4,0.12
1,LCV-3055,15,1,47.12,-7.16,2.60,1.57,2.4,0.38
2,FCV-3040,50,46,137.37,602.40,2.60,3.36,2.4,0.33
3,FCV-0120,250,134,549.00,242.00,3.60,6.12,2.6,1.50
4,FCV-4061,120,76,335.00,536.52,2.42,1.44,2.4,0.31
5,LCV-4030,100,16,180.22,75.41,2.60,2.05,2.4,0.18
6,PCV-7050,44,25,549.78,294.80,2.42,1.00,2.4,0.14
7,LCV-6040,149,34,109.96,400.52,2.60,1.30,2.4,0.51
8,TCV-6050,120,94,251.33,802.28,2.60,1.12,2.4,0.26
9,PCV-7070,44,25,549.78,266.37,2.60,0.87,2.4,0.17
10,TCV-6020,75,50,350.00,275.40,2.60,2.20,2.4,0.08
11,TCV-4100,44,44,579.48,1185.61,2.60,1.26,2.4,0.12
12,LCV-4150,60,51,549.78,632.90,2.60,2.16,2.4,0.53
13,FCV-4120,31,62,137.37,735.72,2.42,1.46,2.4,0.42
14,TCV-4070,0,0,450.00,77.00,3.60,7.37,2.4,11.28
15,PCV-7030,60,19,221.00,140.59,2.60,1.19,2.4,0.20
16,LCV-4020,50,59,137.37,71.59,2.60,2.07,2.4,0.17
17,PCV-4005,60,121,94.25,631.77,2.42,1.47,2.4,0.53
18,PCV-5002,0,0,150.00,117.00,3.60,1.64,2.6,0.11
19,PCV-1301,60,39,235.48,654.50,2.60,1.55,2.0,0.43
20,PCV-6040,120,35,221.00,1945.60,2.60,2.76,2.4,0.11
21,PCV-4020,44,47,549.78,558.01,2.60,2.96,2.4,0.11

In [19]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\dally\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\dally\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dally\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dally\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dally\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [20]:

# CALCULAR PUNTUACIONES INDIVIDUALES POR PARÁMETRO

print("CALCULANDO PUNTUACIONES INDIVIDUALES")

# 1. PUNTUACIÓN DE FRICCIÓN

# Criterios:
# - Normal (1): desviación ≤ 5 unidades
# - Moderado (2): desviación entre 5 y 10 unidades
# - Severo (3): desviación > 10 unidades

df_diagnostico['punt_friccion'] = df_diagnostico.apply(
    lambda x: 1 if abs(x['FRICCION MEDIDA'] - x['FRICCION RECOMENDADA']) <= 5 else
              2 if abs(x['FRICCION MEDIDA'] - x['FRICCION RECOMENDADA']) <= 10 else 3,
    axis=1
)
print(" punt_friccion calculada")

# 2. PUNTUACIÓN DE CARGA EN ASIENTO / TORQUE

# Criterios:
# - Normal (1): desviación ≤ 10%
# - Moderado (2): desviación entre 10% y 25%
# - Severo (3): desviación > 25%

df_diagnostico['punt_carga'] = df_diagnostico.apply(
    lambda x: 1 if abs((x['TORQUE - CARGA EN EL ASIENTO MEDIDA'] / x['TORQUE - CARGA EN EL ASIENTO RECOMENDADA'] - 1) * 100) <= 10 else
              2 if abs((x['TORQUE - CARGA EN EL ASIENTO MEDIDA'] / x['TORQUE - CARGA EN EL ASIENTO RECOMENDADA'] - 1) * 100) <= 25 else 3,
    axis=1
)
print(" punt_carga calculada")


# 3. PUNTUACIÓN DE BANDA MUERTA

# Criterios:
# - Normal (1): medido ≤ recomendado
# - Moderado (2): medido > recomendado pero ≤ 20% sobre
# - Severo (3): medido > 20% sobre el valor recomendado

df_diagnostico['punt_banda'] = df_diagnostico.apply(
    lambda x: 1 if x['BANDA DE ERROR DINAMICA MEDIDA'] <= x['BANDA DE ERROR DINAMICA RECOMENDADA'] else
              2 if x['BANDA DE ERROR DINAMICA MEDIDA'] <= x['BANDA DE ERROR DINAMICA RECOMENDADA'] * 1.2 else 3,
    axis=1
)
print(" punt_banda calculada")


# 4. PUNTUACIÓN DE LINEALIDAD DINÁMICA

# Criterios:
# - Normal (1): medido ≤ recomendado
# - Moderado (2): medido > recomendado pero ≤ 30% sobre
# - Severo (3): medido > 30% sobre el valor recomendado

df_diagnostico['punt_linealidad'] = df_diagnostico.apply(
    lambda x: 1 if x['LINEALIDAD DINAMICA MEDIDA'] <= x['LINEALIDAD DINAMICA RECOMENDADA'] else
              2 if x['LINEALIDAD DINAMICA MEDIDA'] <= x['LINEALIDAD DINAMICA RECOMENDADA'] * 1.3 else 3,
    axis=1
)
print(" punt_linealidad calculada")


# VERIFICAR QUE TODAS LAS COLUMNAS EXISTEN

print("VERIFICACIÓN DE COLUMNAS CREADAS")

columnas_puntuacion = ['punt_friccion', 'punt_carga', 'punt_banda', 'punt_linealidad']
for col in columnas_puntuacion:
    if col in df_diagnostico.columns:
        print(f" {col}: creada correctamente")
        print(f"   Valores únicos: {sorted(df_diagnostico[col].unique())}")
    else:
        print(f" {col}: NO encontrada")

# Mostrar resumen de las puntuaciones
print("\n RESUMEN DE PUNTUACIONES:")

print(df_diagnostico[['TAG CUERPO'] + columnas_puntuacion].head(22))

CALCULANDO PUNTUACIONES INDIVIDUALES
 punt_friccion calculada
 punt_carga calculada
 punt_banda calculada
 punt_linealidad calculada
VERIFICACIÓN DE COLUMNAS CREADAS
 punt_friccion: creada correctamente
   Valores únicos: [np.int64(1), np.int64(2), np.int64(3)]
 punt_carga: creada correctamente
   Valores únicos: [np.int64(1), np.int64(2), np.int64(3)]
 punt_banda: creada correctamente
   Valores únicos: [np.int64(1), np.int64(2), np.int64(3)]
 punt_linealidad: creada correctamente
   Valores únicos: [np.int64(1), np.int64(3)]

 RESUMEN DE PUNTUACIONES:
   TAG CUERPO  punt_friccion  punt_carga  punt_banda  punt_linealidad
0    PCV-5001              3           3           1                1
1    LCV-3055              3           3           1                1
2    FCV-3040              1           3           3                1
3    FCV-0120              3           3           3                1
4    FCV-4061              3           3           1                1
5    LCV-4030              3           3           1                1
6    PCV-7050              3           3           1                1
7    LCV-6040              3           3           1                1
8    TCV-6050              3           3           1                1
9    PCV-7070              3           3           1                1
10   TCV-6020              3           2           1                1
11   TCV-4100              1           3           1                1
12   LCV-4150              2           2           1                1
13   FCV-4120              3           3           1                1
14   TCV-4070              1           3           3                3
15   PCV-7030              3           3           1                1
16   LCV-4020              2           3           1                1
17   PCV-4005              3           3           1                1
18   PCV-5002              1           2           1                1
19   PCV-1301              3           3           1                1
20   PCV-6040              3           3           2                1
21   PCV-4020              1           1           2                1

In [21]:

# CLASIFICACIÓN DE ESTADOS (VERDE, AMARILLO, NARANJA)

def clasificar_estado_valvula(friccion, carga, banda, linealidad):
    """
    Clasifica el estado de la válvula según los criterios definidos.
    
    Parámetros:
    - friccion: 1=Normal, 2=Moderado, 3=Severo
    - carga: 1=Normal, 2=Moderado, 3=Severo
    - banda: 1=Normal, 2=Moderado, 3=Severo
    - linealidad: 1=Normal, 2=Moderado, 3=Severo
    """
    
    #  CASOS ACEPTABLE (VERDE) 
    
    # Caso 1: Todos normales
    if friccion == 1 and carga == 1 and banda == 1 and linealidad == 1:
        return ("ACEPTABLE", " VERDE", "Todos los parámetros dentro de especificaciones")
    
    # Caso 2: Fricción/carga normales, banda/linealidad moderados
    if friccion == 1 and carga == 1 and banda == 2 and linealidad == 2:
        return ("ACEPTABLE", " VERDE", "Problema en posicionador - requiere pequeña calibración")
    
    #  CASOS ACEPTABLE CON COMENTARIOS (AMARILLO) 
    
    # Caso 3: Fricción/carga moderados, banda/linealidad normales
    if friccion == 2 and carga == 2 and banda == 1 and linealidad == 1:
        return ("ACEPTABLE CON COMENTARIOS", " AMARILLO", "Problema mecánico en cuerpo/actuador - intervención preventiva")
    
    # Caso 4: Todos moderados
    if friccion == 2 and carga == 2 and banda == 2 and linealidad == 2:
        return ("ACEPTABLE CON COMENTARIOS", " AMARILLO", "Problema generalizado - intervención integral")
    
    #  CASOS ALERTA (NARANJA) 
    
    # Caso 5: Fricción/carga severos, banda/linealidad normales
    if friccion == 3 and carga == 3 and banda == 1 and linealidad == 1:
        return ("ALERTA", " NARANJA", "Desgaste severo en asiento y tapón - inspección urgente")
    
    # Caso 6: Fricción/carga severos, banda/linealidad moderados
    if friccion == 3 and carga == 3 and banda == 2 and linealidad == 2:
        return ("ALERTA", " NARANJA", "Fallo mecánico crítico - intervención prioritaria")
    
    # Caso 7: Banda/linealidad severos, fricción/carga normales
    if friccion == 1 and carga == 1 and banda == 3 and linealidad == 3:
        return ("ALERTA", " NARANJA", "Problema grave en posicionador - revisar urgentemente")
    
    # Caso 8: Fricción/carga moderados, banda/linealidad severos
    if friccion == 2 and carga == 2 and banda == 3 and linealidad == 3:
        return ("ALERTA", " NARANJA", "Problema combinado mecánico+control - intervención completa")
    
    # Caso 9: Todos severos
    if friccion == 3 and carga == 3 and banda == 3 and linealidad == 3:
        return ("ALERTA", " NARANJA", "Fallo crítico generalizado - parada inmediata")
    
    # Cualquier otra combinación
    else:
        return ("ACEPTABLE CON COMENTARIOS", " AMARILLO", f"Combinación no estándar - requiere análisis adicional")

print(" Función de clasificación definida")

# APLICAR CLASIFICACIÓN A LOS DATOS

# Verificar que las columnas de puntuación existen
columnas_puntuacion = ['punt_friccion', 'punt_carga', 'punt_banda', 'punt_linealidad']
for col in columnas_puntuacion:
    if col not in df_diagnostico.columns:
        print(f" Error: Falta la columna '{col}'")
        print("   Primero debes calcular las puntuaciones")
        break
else:
    # Aplicar clasificación
    df_diagnostico[['estado_valvula', 'color_estado', 'mensaje_estado']] = df_diagnostico.apply(
        lambda x: clasificar_estado_valvula(
            x['punt_friccion'], x['punt_carga'], x['punt_banda'], x['punt_linealidad']
        ), axis=1, result_type='expand'
    )
    
    print(" Clasificación aplicada correctamente")
    
    # Mostrar resultados
    print("\n RESULTADOS DE CLASIFICACIÓN:")
    print(df_diagnostico[['TAG CUERPO', 'punt_friccion', 'punt_carga', 
                          'punt_banda', 'punt_linealidad', 'estado_valvula', 'color_estado']].head(25))
    
    # Mostrar distribución
    print("\n DISTRIBUCIÓN DE ESTADOS:")
    print(df_diagnostico['estado_valvula'].value_counts())

 Función de clasificación definida
 Clasificación aplicada correctamente

 RESULTADOS DE CLASIFICACIÓN:
   TAG CUERPO  punt_friccion  punt_carga  punt_banda  punt_linealidad  \
0    PCV-5001              3           3           1                1
1    LCV-3055              3           3           1                1
2    FCV-3040              1           3           3                1
3    FCV-0120              3           3           3                1
4    FCV-4061              3           3           1                1
5    LCV-4030              3           3           1                1
6    PCV-7050              3           3           1                1
7    LCV-6040              3           3           1                1
8    TCV-6050              3           3           1                1
9    PCV-7070              3           3           1                1
10   TCV-6020              3           2           1                1
11   TCV-4100              1           3           1                1
12   LCV-4150              2           2           1                1
13   FCV-4120              3           3           1                1
14   TCV-4070              1           3           3                3
15   PCV-7030              3           3           1                1
16   LCV-4020              2           3           1                1
17   PCV-4005              3           3           1                1
18   PCV-5002              1           2           1                1
19   PCV-1301              3           3           1                1
20   PCV-6040              3           3           2                1
21   PCV-4020              1           1           2                1

               estado_valvula color_estado
0                      ALERTA      NARANJA
1                      ALERTA      NARANJA
2   ACEPTABLE CON COMENTARIOS     AMARILLO
3   ACEPTABLE CON COMENTARIOS     AMARILLO
4                      ALERTA      NARANJA
5                      ALERTA      NARANJA
6                      ALERTA      NARANJA
7                      ALERTA      NARANJA
8                      ALERTA      NARANJA
9                      ALERTA      NARANJA
10  ACEPTABLE CON COMENTARIOS     AMARILLO
11  ACEPTABLE CON COMENTARIOS     AMARILLO
12  ACEPTABLE CON COMENTARIOS     AMARILLO
13                     ALERTA      NARANJA
14  ACEPTABLE CON COMENTARIOS     AMARILLO
15                     ALERTA      NARANJA
16  ACEPTABLE CON COMENTARIOS     AMARILLO
17                     ALERTA      NARANJA
18  ACEPTABLE CON COMENTARIOS     AMARILLO
19                     ALERTA      NARANJA
20  ACEPTABLE CON COMENTARIOS     AMARILLO
21  ACEPTABLE CON COMENTARIOS     AMARILLO

 DISTRIBUCIÓN DE ESTADOS:
estado_valvula
ALERTA                       12
ACEPTABLE CON COMENTARIOS    10
Name: count, dtype: int64

In [22]:
# MODELO DE MACHINE LEARNING

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Verificar que la columna estado_valvula existe
if 'estado_valvula' not in df_diagnostico.columns:
    print(" Error: Primero debes ejecutar la clasificación de estados")
else:
    # Características
    features = [
        'FRICCION RECOMENDADA', 'FRICCION MEDIDA',
        'TORQUE - CARGA EN EL ASIENTO RECOMENDADA', 'TORQUE - CARGA EN EL ASIENTO MEDIDA',
        'BANDA DE ERROR DINAMICA RECOMENDADA', 'BANDA DE ERROR DINAMICA MEDIDA',
        'LINEALIDAD DINAMICA RECOMENDADA', 'LINEALIDAD DINAMICA MEDIDA'
    ]
    
    X = df_diagnostico[features]
    y = df_diagnostico['estado_valvula']
    
    print(f" Datos: {X.shape[0]} válvulas, {X.shape[1]} características")
    print(f" Clases: {y.unique().tolist()}")
    print(f"\n Distribución de clases:")
    print(y.value_counts())
    
    # Dividir datos
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )
    
    # Escalar
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    # Entrenar Random Forest
    rf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
    rf.fit(X_train_scaled, y_train)
    y_pred = rf.predict(X_test_scaled)
    
    print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.2f}")
    print("\nReporte de clasificación:")
    print(classification_report(y_test, y_pred))

 Datos: 22 válvulas, 8 características
 Clases: ['ALERTA', 'ACEPTABLE CON COMENTARIOS']

 Distribución de clases:
estado_valvula
ALERTA                       12
ACEPTABLE CON COMENTARIOS    10
Name: count, dtype: int64

Accuracy: 0.71

Reporte de clasificación:
                           precision    recall  f1-score   support

ACEPTABLE CON COMENTARIOS       1.00      0.33      0.50         3
                   ALERTA       0.67      1.00      0.80         4

                 accuracy                           0.71         7
                macro avg       0.83      0.67      0.65         7
             weighted avg       0.81      0.71      0.67         7